### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by vico93** [redfox193/Amethyst-Update#1]
I did a Portuguese (Brazil) language file for Amethist update. [Here](https://gist.github.com/vico93/1bfe7ae4673d97941b5da874af7fdbaa)'s the Gist with the file.

I prefer to share it rather than PR it because i'm not sure about some of the effect names (more specific, _Tampered_ an _Shatterd_), what they mean in the context of the mod and what proper expression should i use in the translation.

But i hope you can use that!

**Comment by redfox193** [comment]
Thanks for your translation! I’ll use it if I add more languages in my mod. I don’t know Portuguese language, therefore your translation is useful😄!
