### ISSUE TITLE
[Suggestion] Amethyst Staff Blacklist

### ISSUE THREAD

**Issue by Ultimushadow** [redfox193/Amethyst-Update#2]
Hey there, love the mod so far, I had an idea for the mod after accidentally damaging one of my pets with the Shattering staff. I thought about maybe having the staff automatically check mobs for an owner or something but that might be an issue when implemented alongside other mods (For instance, the pet I damaged was a dragon from AdventureZ, and it uses a unique tag). So, simplest solution is usually the best, could you add a config or a simple entity group tag that won't be hurt by the staff?

**Comment by redfox193** [comment]
Good idea, I haven't thought about pets. I'll see, how I can implement it in the mod. Thanx:smile:!

**Comment by Ultimushadow** [comment]
Thanks for looking into it!
